export type CountryDataType = {
  name: string;
  dial_code: string;
  code: string;
  emoji: string;
};

const countryList: Array<CountryDataType> = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    emoji: "🇦🇫",
    code: "AF",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    emoji: "🇦🇽",
    code: "AX",
  },
  {
    dial_code: "+355",
    name: "Albania",
    emoji: "🇦🇱",
    code: "AL",
  },
  {
    dial_code: "+213",
    name: "Algeria",
    emoji: "🇩🇿",
    code: "DZ",
  },
  {
    name: "American Samoa",
    dial_code: "+1684",
    emoji: "🇦🇸",
    code: "AS",
  },
  {
    dial_code: "+376",
    name: "Andorra",
    emoji: "🇦🇩",
    code: "AD",
  },
  {
    dial_code: "+244",
    name: "Angola",
    emoji: "🇦🇴",
    code: "AO",
  },
  {
    dial_code: "+1264",
    name: "Anguilla",
    emoji: "🇦🇮",
    code: "AI",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    emoji: "🇦🇶",
    code: "AQ",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    emoji: "🇦🇬",
    code: "AG",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    emoji: "🇦🇷",
    code: "AR",
  },
  {
    dial_code: "+374",
    name: "Armenia",
    emoji: "🇦🇲",
    code: "AM",
  },
  {
    dial_code: "+297",
    emoji: "🇦🇼",
    name: "Aruba",
    code: "AW",
  },
  {
    name: "Australia",
    dial_code: "+61",
    emoji: "🇦🇺",
    code: "AU",
  },
  {
    dial_code: "+43",
    name: "Austria",
    emoji: "🇦🇹",
    code: "AT",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    emoji: "🇦🇿",
    code: "AZ",
  },
  {
    dial_code: "+1242",
    name: "Bahamas",
    emoji: "🇧🇸",
    code: "BS",
  },
  {
    dial_code: "+973",
    name: "Bahrain",
    emoji: "🇧🇭",
    code: "BH",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    emoji: "🇧🇩",
    code: "BD",
  },
  {
    dial_code: "+1246",
    name: "Barbados",
    emoji: "🇧🇧",
    code: "BB",
  },
  {
    dial_code: "+375",
    name: "Belarus",
    emoji: "🇧🇾",
    code: "BY",
  },
  {
    dial_code: "+32",
    name: "Belgium",
    emoji: "🇧🇪",
    code: "BE",
  },
  {
    dial_code: "+501",
    name: "Belize",
    emoji: "🇧🇿",
    code: "BZ",
  },
  {
    dial_code: "+229",
    emoji: "🇧🇯",
    name: "Benin",
    code: "BJ",
  },
  {
    dial_code: "+1441",
    name: "Bermuda",
    emoji: "🇧🇲",
    code: "BM",
  },
  {
    dial_code: "+975",
    name: "Bhutan",
    emoji: "🇧🇹",
    code: "BT",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    emoji: "🇧🇴",
    code: "BO",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    emoji: "🇧🇦",
    code: "BA",
  },
  {
    dial_code: "+267",
    name: "Botswana",
    emoji: "🇧🇼",
    code: "BW",
  },
  {
    dial_code: "+55",
    name: "Brazil",
    emoji: "🇧🇷",
    code: "BR",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    emoji: "🇮🇴",
    code: "IO",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    emoji: "🇧🇳",
    code: "BN",
  },
  {
    dial_code: "+359",
    name: "Bulgaria",
    emoji: "🇧🇬",
    code: "BG",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    emoji: "🇧🇫",
    code: "BF",
  },
  {
    dial_code: "+257",
    name: "Burundi",
    emoji: "🇧🇮",
    code: "BI",
  },
  {
    dial_code: "+855",
    name: "Cambodia",
    emoji: "🇰🇭",
    code: "KH",
  },
  {
    dial_code: "+237",
    name: "Cameroon",
    emoji: "🇨🇲",
    code: "CM",
  },
  {
    dial_code: "+1",
    name: "Canada",
    emoji: "🇨🇦",
    code: "CA",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    emoji: "🇨🇻",
    code: "CV",
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    emoji: "🇰🇾",
    code: "KY",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    emoji: "🇨🇫",
    code: "CF",
  },
  {
    dial_code: "+235",
    emoji: "🇹🇩",
    name: "Chad",
    code: "TD",
  },
  {
    dial_code: "+56",
    emoji: "🇨🇱",
    name: "Chile",
    code: "CL",
  },
  {
    dial_code: "+86",
    emoji: "🇨🇳",
    name: "China",
    code: "CN",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    emoji: "🇨🇽",
    code: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    emoji: "🇨🇨",
    code: "CC",
  },
  {
    dial_code: "+57",
    name: "Colombia",
    emoji: "🇨🇴",
    code: "CO",
  },
  {
    dial_code: "+269",
    name: "Comoros",
    emoji: "🇰🇲",
    code: "KM",
  },
  {
    dial_code: "+242",
    emoji: "🇨🇬",
    name: "Congo",
    code: "CG",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    emoji: "🇨🇩",
    code: "CD",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    emoji: "🇨🇰",
    code: "CK",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    emoji: "🇨🇷",
    code: "CR",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    emoji: "🇨🇮",
    code: "CI",
  },
  {
    dial_code: "+385",
    name: "Croatia",
    emoji: "🇭🇷",
    code: "HR",
  },
  {
    dial_code: "+53",
    emoji: "🇨🇺",
    name: "Cuba",
    code: "CU",
  },
  {
    dial_code: "+357",
    name: "Cyprus",
    emoji: "🇨🇾",
    code: "CY",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    emoji: "🇨🇿",
    code: "CZ",
  },
  {
    dial_code: "+45",
    name: "Denmark",
    emoji: "🇩🇰",
    code: "DK",
  },
  {
    dial_code: "+253",
    name: "Djibouti",
    emoji: "🇩🇯",
    code: "DJ",
  },
  {
    dial_code: "+1767",
    name: "Dominica",
    emoji: "🇩🇲",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    emoji: "🇩🇴",
    code: "DO",
  },
  {
    dial_code: "+593",
    name: "Ecuador",
    emoji: "🇪🇨",
    code: "EC",
  },
  {
    dial_code: "+20",
    emoji: "🇪🇬",
    name: "Egypt",
    code: "EG",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    emoji: "🇸🇻",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    emoji: "🇬🇶",
    code: "GQ",
  },
  {
    dial_code: "+291",
    name: "Eritrea",
    emoji: "🇪🇷",
    code: "ER",
  },
  {
    dial_code: "+372",
    name: "Estonia",
    emoji: "🇪🇪",
    code: "EE",
  },
  {
    dial_code: "+251",
    name: "Ethiopia",
    emoji: "🇪🇹",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    emoji: "🇫🇰",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    emoji: "🇫🇴",
    code: "FO",
  },
  {
    dial_code: "+679",
    emoji: "🇫🇯",
    name: "Fiji",
    code: "FJ",
  },
  {
    dial_code: "+358",
    name: "Finland",
    emoji: "🇫🇮",
    code: "FI",
  },
  {
    dial_code: "+33",
    name: "France",
    emoji: "🇫🇷",
    code: "FR",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    emoji: "🇬🇫",
    code: "GF",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    emoji: "🇵🇫",
    code: "PF",
  },
  {
    dial_code: "+241",
    emoji: "🇬🇦",
    name: "Gabon",
    code: "GA",
  },
  {
    dial_code: "+220",
    name: "Gambia",
    emoji: "🇬🇲",
    code: "GM",
  },
  {
    dial_code: "+995",
    name: "Georgia",
    emoji: "🇬🇪",
    code: "GE",
  },
  {
    dial_code: "+49",
    name: "Germany",
    emoji: "🇩🇪",
    code: "DE",
  },
  {
    dial_code: "+233",
    emoji: "🇬🇭",
    name: "Ghana",
    code: "GH",
  },
  {
    dial_code: "+350",
    name: "Gibraltar",
    emoji: "🇬🇮",
    code: "GI",
  },
  {
    dial_code: "+30",
    name: "Greece",
    emoji: "🇬🇷",
    code: "GR",
  },
  {
    dial_code: "+299",
    name: "Greenland",
    emoji: "🇬🇱",
    code: "GL",
  },
  {
    dial_code: "+1473",
    name: "Grenada",
    emoji: "🇬🇩",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    emoji: "🇬🇵",
    code: "GP",
  },
  {
    dial_code: "+1671",
    emoji: "🇬🇺",
    name: "Guam",
    code: "GU",
  },
  {
    dial_code: "+502",
    name: "Guatemala",
    emoji: "🇬🇹",
    code: "GT",
  },
  {
    dial_code: "+44",
    name: "Guernsey",
    emoji: "🇬🇬",
    code: "GG",
  },
  {
    dial_code: "+224",
    name: "Guinea",
    emoji: "🇬🇳",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    emoji: "🇬🇼",
    code: "GW",
  },
  {
    dial_code: "+595",
    name: "Guyana",
    emoji: "🇬🇾",
    code: "GY",
  },
  {
    dial_code: "+509",
    emoji: "🇭🇹",
    name: "Haiti",
    code: "HT",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    emoji: "🇻🇦",
    code: "VA",
  },
  {
    dial_code: "+504",
    name: "Honduras",
    emoji: "🇭🇳",
    code: "HN",
  },
  {
    dial_code: "+852",
    name: "Hong Kong",
    emoji: "🇭🇰",
    code: "HK",
  },
  {
    dial_code: "+36",
    name: "Hungary",
    emoji: "🇭🇺",
    code: "HU",
  },
  {
    dial_code: "+354",
    name: "Iceland",
    emoji: "🇮🇸",
    code: "IS",
  },
  {
    dial_code: "+91",
    emoji: "🇮🇳",
    name: "India",
    code: "IN",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    emoji: "🇮🇩",
    code: "ID",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    emoji: "🇮🇷",
    code: "IR",
  },
  {
    dial_code: "+964",
    emoji: "🇮🇶",
    name: "Iraq",
    code: "IQ",
  },
  {
    dial_code: "+353",
    name: "Ireland",
    emoji: "🇮🇪",
    code: "IE",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    emoji: "🇮🇲",
    code: "IM",
  },
  {
    dial_code: "+972",
    name: "Israel",
    emoji: "🇮🇱",
    code: "IL",
  },
  {
    dial_code: "+39",
    emoji: "🇮🇹",
    name: "Italy",
    code: "IT",
  },
  {
    dial_code: "+1876",
    name: "Jamaica",
    emoji: "🇯🇲",
    code: "JM",
  },
  {
    dial_code: "+81",
    name: "Japan",
    emoji: "🗾",
    code: "JP",
  },
  {
    dial_code: "+44",
    name: "Jersey",
    emoji: "🇯🇪",
    code: "JE",
  },
  {
    dial_code: "+962",
    name: "Jordan",
    emoji: "🇯🇴",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    emoji: "🇰🇿",
    code: "KZ",
  },
  {
    dial_code: "+254",
    emoji: "🇰🇪",
    name: "Kenya",
    code: "KE",
  },
  {
    dial_code: "+686",
    name: "Kiribati",
    emoji: "🇰🇮",
    code: "KI",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    emoji: "🇰🇵",
    code: "KP",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    emoji: "🇰🇷",
    code: "KR",
  },
  {
    dial_code: "+965",
    name: "Kuwait",
    emoji: "🇰🇼",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    emoji: "🇰🇬",
    code: "KG",
  },
  {
    dial_code: "+856",
    emoji: "🇱🇦",
    name: "Laos",
    code: "LA",
  },
  {
    dial_code: "+371",
    name: "Latvia",
    emoji: "🇱🇻",
    code: "LV",
  },
  {
    dial_code: "+961",
    name: "Lebanon",
    emoji: "🇱🇧",
    code: "LB",
  },
  {
    dial_code: "+266",
    name: "Lesotho",
    emoji: "🇱🇸",
    code: "LS",
  },
  {
    dial_code: "+231",
    name: "Liberia",
    emoji: "🇱🇷",
    code: "LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    emoji: "🇱🇾",
    code: "LY",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    emoji: "🇱🇮",
    code: "LI",
  },
  {
    dial_code: "+370",
    name: "Lithuania",
    emoji: "🇱🇹",
    code: "LT",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    emoji: "🇱🇺",
    code: "LU",
  },
  {
    dial_code: "+853",
    emoji: "🇲🇴",
    name: "Macao",
    code: "MO",
  },
  {
    dial_code: "+389",
    name: "Macedonia",
    emoji: "🇲🇰",
    code: "MK",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    emoji: "🇲🇬",
    code: "MG",
  },
  {
    dial_code: "+265",
    name: "Malawi",
    emoji: "🇲🇼",
    code: "MW",
  },
  {
    dial_code: "+60",
    name: "Malaysia",
    emoji: "🇲🇾",
    code: "MY",
  },
  {
    dial_code: "+960",
    name: "Maldives",
    emoji: "🇲🇻",
    code: "MV",
  },
  {
    dial_code: "+223",
    emoji: "🇲🇱",
    name: "Mali",
    code: "ML",
  },
  {
    dial_code: "+356",
    emoji: "🇲🇹",
    name: "Malta",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    emoji: "🇲🇭",
    code: "MH",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    emoji: "🇲🇶",
    code: "MQ",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    emoji: "🇲🇷",
    code: "MR",
  },
  {
    dial_code: "+230",
    name: "Mauritius",
    emoji: "🇲🇺",
    code: "MU",
  },
  {
    dial_code: "+262",
    name: "Mayotte",
    emoji: "🇾🇹",
    code: "YT",
  },
  {
    dial_code: "+52",
    name: "Mexico",
    emoji: "🇲🇽",
    code: "MX",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    emoji: "🇫🇲",
    code: "FM",
  },
  {
    dial_code: "+373",
    name: "Moldova",
    emoji: "🇲🇩",
    code: "MD",
  },
  {
    dial_code: "+377",
    name: "Monaco",
    emoji: "🇲🇨",
    code: "MC",
  },
  {
    dial_code: "+976",
    name: "Mongolia",
    emoji: "🇲🇳",
    code: "MN",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    emoji: "🇲🇪",
    code: "ME",
  },
  {
    dial_code: "+1664",
    name: "Montserrat",
    emoji: "🇲🇸",
    code: "MS",
  },
  {
    dial_code: "+212",
    name: "Morocco",
    emoji: "🇲🇦",
    code: "MA",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    emoji: "🇲🇿",
    code: "MZ",
  },
  {
    dial_code: "+95",
    name: "Myanmar",
    emoji: "🇲🇲",
    code: "MM",
  },
  {
    dial_code: "+264",
    name: "Namibia",
    emoji: "🇳🇦",
    code: "NA",
  },
  {
    dial_code: "+674",
    emoji: "🇳🇷",
    name: "Nauru",
    code: "NR",
  },
  {
    dial_code: "+977",
    emoji: "🇳🇵",
    name: "Nepal",
    code: "NP",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    emoji: "🇳🇱",
    code: "NL",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    emoji: "🇳🇱",
    code: "AN",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    emoji: "🇳🇨",
    code: "NC",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    emoji: "🇳🇿",
    code: "NZ",
  },
  {
    dial_code: "+505",
    name: "Nicaragua",
    emoji: "🇳🇮",
    code: "NI",
  },
  {
    dial_code: "+227",
    emoji: "🇳🇪",
    name: "Niger",
    code: "NE",
  },
  {
    dial_code: "+234",
    name: "Nigeria",
    emoji: "🇳🇬",
    code: "NG",
  },
  {
    dial_code: "+683",
    emoji: "🇳🇺",
    name: "Niue",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    emoji: "🇳🇫",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    emoji: "🇲🇵",
    code: "MP",
  },
  {
    dial_code: "+47",
    name: "Norway",
    emoji: "🇳🇴",
    code: "NO",
  },
  {
    dial_code: "+968",
    emoji: "🇴🇲",
    name: "Oman",
    code: "OM",
  },
  {
    dial_code: "+92",
    name: "Pakistan",
    emoji: "🇵🇰",
    code: "PK",
  },
  {
    dial_code: "+680",
    emoji: "🇵🇼",
    name: "Palau",
    code: "PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    emoji: "🇵🇸",
    code: "PS",
  },
  {
    dial_code: "+507",
    name: "Panama",
    emoji: "🇵🇦",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    emoji: "🇵🇬",
    code: "PG",
  },
  {
    dial_code: "+595",
    name: "Paraguay",
    emoji: "🇵🇾",
    code: "PY",
  },
  {
    dial_code: "+51",
    emoji: "🇵🇪",
    name: "Peru",
    code: "PE",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    emoji: "🇵🇭",
    code: "PH",
  },
  {
    dial_code: "+872",
    name: "Pitcairn",
    emoji: "🇵🇳",
    code: "PN",
  },
  {
    dial_code: "+48",
    name: "Poland",
    emoji: "🇵🇱",
    code: "PL",
  },
  {
    dial_code: "+351",
    name: "Portugal",
    emoji: "🇵🇹",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    emoji: "🇵🇷",
    code: "PR",
  },
  {
    dial_code: "+974",
    emoji: "🇶🇦",
    name: "Qatar",
    code: "QA",
  },
  {
    dial_code: "+40",
    name: "Romania",
    emoji: "🇷🇴",
    code: "RO",
  },
  {
    dial_code: "+7",
    name: "Russia",
    emoji: "🇷🇺",
    code: "RU",
  },
  {
    dial_code: "+250",
    name: "Rwanda",
    emoji: "🇷🇼",
    code: "RW",
  },
  {
    dial_code: "+262",
    name: "Reunion",
    emoji: "🇷🇪",
    code: "RE",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    emoji: "🇧🇱",
    code: "BL",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    emoji: "🇸🇭",
    code: "SH",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    emoji: "🇰🇳",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    emoji: "🇱🇨",
    code: "LC",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    emoji: "🇫🇷",
    code: "MF",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    emoji: "🇵🇲",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    emoji: "🇻🇨",
    code: "VC",
  },
  {
    dial_code: "+685",
    emoji: "🇼🇸",
    name: "Samoa",
    code: "WS",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    emoji: "🇸🇲",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    emoji: "🇸🇹",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    emoji: "🇸🇦",
    code: "SA",
  },
  {
    dial_code: "+221",
    name: "Senegal",
    emoji: "🇸🇳",
    code: "SN",
  },
  {
    dial_code: "+381",
    name: "Serbia",
    emoji: "🇷🇸",
    code: "RS",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    emoji: "🇸🇨",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    emoji: "🇸🇱",
    code: "SL",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    emoji: "🇸🇬",
    code: "SG",
  },
  {
    dial_code: "+421",
    name: "Slovakia",
    emoji: "🇸🇰",
    code: "SK",
  },
  {
    dial_code: "+386",
    name: "Slovenia",
    emoji: "🇸🇮",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    emoji: "🇸🇧",
    code: "SB",
  },
  {
    dial_code: "+252",
    name: "Somalia",
    emoji: "🇸🇴",
    code: "SO",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    emoji: "🇿🇦",
    code: "ZA",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    emoji: "🇸🇸",
    code: "SS",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    emoji: "🇬🇸",
    code: "GS",
  },
  {
    dial_code: "+34",
    emoji: "🇪🇸",
    name: "Spain",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    emoji: "🇱🇰",
    code: "LK",
  },
  {
    dial_code: "+249",
    emoji: "🇸🇩",
    name: "Sudan",
    code: "SD",
  },
  {
    dial_code: "+597",
    name: "Suriname",
    emoji: "🇸🇷",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    emoji: "🇳🇴",
    code: "SJ",
  },
  {
    dial_code: "+268",
    name: "Swaziland",
    emoji: "🇸🇿",
    code: "SZ",
  },
  {
    dial_code: "+46",
    name: "Sweden",
    emoji: "🇸🇪",
    code: "SE",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    emoji: "🇨🇭",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    emoji: "🇸🇾",
    code: "SY",
  },
  {
    dial_code: "+886",
    name: "Taiwan",
    emoji: "🇹🇼",
    code: "TW",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    emoji: "🇹🇯",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    emoji: "🇹🇿",
    code: "TZ",
  },
  {
    dial_code: "+66",
    name: "Thailand",
    emoji: "🇹🇭",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    emoji: "🇹🇱",
    code: "TL",
  },
  {
    dial_code: "+228",
    emoji: "🇹🇬",
    name: "Togo",
    code: "TG",
  },
  {
    dial_code: "+690",
    name: "Tokelau",
    emoji: "🇹🇰",
    code: "TK",
  },
  {
    dial_code: "+676",
    emoji: "🇹🇴",
    name: "Tonga",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    emoji: "🇹🇹",
    code: "TT",
  },
  {
    dial_code: "+216",
    name: "Tunisia",
    emoji: "🇹🇳",
    code: "TN",
  },
  {
    dial_code: "+90",
    name: "Turkey",
    emoji: "🇹🇷",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    emoji: "🇹🇲",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    emoji: "🇹🇨",
    code: "TC",
  },
  {
    dial_code: "+688",
    name: "Tuvalu",
    emoji: "🇹🇻",
    code: "TV",
  },
  {
    dial_code: "+256",
    name: "Uganda",
    emoji: "🇺🇬",
    code: "UG",
  },
  {
    dial_code: "+380",
    name: "Ukraine",
    emoji: "🇺🇦",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    emoji: "🇦🇪",
    code: "AE",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    emoji: "🇬🇧",
    code: "UK",
  },
  {
    name: "United States",
    dial_code: "+1",
    emoji: "🇺🇸",
    code: "US",
  },
  {
    dial_code: "+598",
    name: "Uruguay",
    emoji: "🇺🇾",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    emoji: "🇺🇿",
    code: "UZ",
  },
  {
    dial_code: "+678",
    name: "Vanuatu",
    emoji: "🇻🇺",
    code: "VU",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    emoji: "🇻🇪",
    code: "VE",
  },
  {
    dial_code: "+84",
    name: "Vietnam",
    emoji: "🇻🇳",
    code: "VN",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    emoji: "🇻🇬",
    code: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    emoji: "🇻🇮",
    code: "VI",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    emoji: "🇼🇫",
    code: "WF",
  },
  {
    dial_code: "+967",
    emoji: "🇾🇪",
    name: "Yemen",
    code: "YE",
  },
  {
    dial_code: "+260",
    name: "Zambia",
    emoji: "🇿🇲",
    code: "ZM",
  },
  {
    dial_code: "+263",
    name: "Zimbabwe",
    emoji: "🇿🇼",
    code: "ZW",
  },
];

export default countryList;
